# New ports collection makefile for: d-mon2
# Date created:        27 Jan 2004
# Whom:                dmitry@karasik.eu.org
#
# $FreeBSD$
#

PORTNAME=	spansk

MAINTAINER=	m@kjeldsen.me
COMMENT=	spansk

RUN_DEPENDS = \
		${SITE_PERL}/${PERL_ARCH}/List/MoreUtils.pm:${PORTSDIR}/lang/p5-List-MoreUtils #\
#		${SITE_PERL}/EV.pm:${PORTSDIR}/devel/p5-EV

.include <bsd.port.pre.mk>

.include <bsd.port.post.mk>
